export { default as Dashbored } from './dashbored/dashbored';
export { default as Login } from './login';
export { default as AuthenticatedError } from './pagesError/authenticatedError';
export { default as AuthorizedError } from './pagesError/authorizedError';
export { default as Home } from './dashbored/pages/home';
export { default as Categorie } from './dashbored/pages/categorie';
export { default as SousCategorie } from './dashbored/pages/sousCategorie';
export { default as SousSousCategorie } from './dashbored/pages/sousSousCategorie';
export { default as Forniseur } from './dashbored/pages/forniseur'
export { default as Marque } from '../page/dashbored/pages/marque'
export { default as Produit } from '../page/dashbored/pages/produit'